import puppeteer from "puppeteer-core";
const CHROME = "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const BASE = "https://blogstudio-ide.asia";
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
const b = await puppeteer.launch({ executablePath: CHROME, headless: "new", args: ["--no-sandbox"] });
const p = await b.newPage();
await p.goto(`${BASE}/login`, { waitUntil: "networkidle0" });
await p.type('input[name="email"]', "admin@blogstudio.local");
await p.type('input[name="password"]', "studio1234!");
await Promise.all([p.click('button[type="submit"]'), p.waitForNavigation({ waitUntil: "networkidle0" }).catch(() => {})]);
await sleep(1000);
await p.goto(`${BASE}/blogs`, { waitUntil: "networkidle0" }).catch(()=>{});
await sleep(1500);
const links = await p.evaluate(() => [...document.querySelectorAll('a[href*="/blogs/"]')].map(a => ({href:a.getAttribute('href'), text:a.innerText.trim().replace(/\s+/g,' ').slice(0,70)})).filter(x=>/\/blogs\/[A-Za-z0-9_-]{6,}/.test(x.href)));
console.log("BLOG_LINKS:", JSON.stringify(links, null, 1));
await b.close();
