import puppeteer from "puppeteer-core";
const CHROME="/Users/ideagent/Library/Caches/ms-playwright/chromium_headless_shell-1228/chrome-headless-shell-mac-arm64/chrome-headless-shell";
const BASE="https://blogstudio-ide.asia"; const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const b=await puppeteer.launch({executablePath:CHROME,headless:true,args:["--no-sandbox"]});
const p=await b.newPage(); await p.setViewport({width:1400,height:2000});
await p.goto(`${BASE}/login`,{waitUntil:"networkidle0"});
await p.type('input[name="email"]',"admin@blogstudio.local");
await p.type('input[name="password"]',"studio1234!");
await Promise.all([p.click('button[type="submit"]'),p.waitForNavigation({waitUntil:"networkidle0"}).catch(()=>{})]);
await sleep(800);
await p.goto(`${BASE}/blogs`,{waitUntil:"networkidle0"}).catch(()=>{});
await sleep(600);
const links=await p.evaluate(()=>[...new Set([...document.querySelectorAll('a')].map(a=>a.getAttribute('href')).filter(Boolean))]);
console.log("LINKS:",JSON.stringify(links.filter(h=>/blog|queue/i.test(h)).slice(0,25)));
const ids=await p.evaluate(()=>[...new Set([...document.querySelectorAll('a')].map(a=>a.getAttribute('href')||'').map(h=>(h.match(/blogId=([A-Za-z0-9]{6,})/)||h.match(/\/blogs\/([A-Za-z0-9]{6,})/)||[])[1]).filter(Boolean))]);
console.log("IDS:",JSON.stringify(ids));
await b.close();
